[tool.poetry]
name = "msys2-updator"
version = "0.1.0"
description = "Update packages in msys2 repos."
authors = ["Naveen M K <naveen@syrusdark.website>"]
license = "MIT"
packages = [
    { include = "updator" },
]

[tool.poetry.dependencies]
python = "^3.7"
PyGithub = "^1.55"
python-gitlab = "^2.9"
requests="^2.25"
rich = "^10.5.0"
packaging = "^21.0"
GitPython = "^3.1.18"
johnnydep = "^1.8"

[tool.poetry.dev-dependencies]
black = {version = "^21.7b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
