[tool.poetry]
name = "msys2-updator"
version = "0.1.0"
description = "Update packages in msys2 repos."
authors = ["Naveen M K <naveen@syrusdark.website>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
PyGithub = "^1.54"
python-gitlab = "^2.6"
requests="^2.25"
rich = "^9.11.0"
packaging = "^20.9"
GitPython = "^3.1.13"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
