name: update

on:
  push:
  workflow_dispatch:
jobs:
  update:
    runs-on: windows-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
      PYTHONIOENCODING: utf-8
    steps:
    - uses: actions/checkout@v2
      with:
        path: updator
    - name: Clone MINGW
      uses: actions/checkout@v2
      with:
        repository: msys2/MINGW-packages
        ref: master
        path: "MINGW-packages"
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: updator
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Run Updator
      shell: bash
      working-directory: updator
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        python -m updator
    - name: "Upload logs"
      uses: actions/upload-artifact@v2
      with:
          name: logs
          path: updator/*.log
    - name: Get Commit Message
      id: message
      shell: bash
      working-directory: updator
      run: |
          python utils/commit_message.py
    - name: Commit
      shell: bash
      env:
        commit_message: ${{ steps.message.outputs.commit_message }}
      working-directory: MINGW-packages
      run: |
        git remote add fork https://github.com/naveen521kk/MINGW-packages.git
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        message=$(python utils/commit_message.py)
        git commit -am "${commit_message}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN_PUSH }}
        branch: update
        force: true
        directory: MINGW-packages
        repository: naveen521kk/MINGW-packages
